

             arithmeticTerm  ::=  rationalNumber ;


             rationalNumber  ::=  integer<NO_WHITESPACE>"/"<NO_WHITESPACE>integer

                               |  [name]

                               ;


